/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Administrador;
import Clase.Docente;
import Clase.Estado;
import Modelo.BaseDeDatos;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovanni
 */
public class VAdmDocentesEliminados extends javax.swing.JFrame {
    private Docente docente;
    private int numFilaSeleccionada;
    
    private final String CRITERIO_MATRICULA = "pkId";
    private final String CRITERIO_NOMBRE = "Nombre";
    
    private BaseDeDatos bd = new BaseDeDatos();
    
    /**
     * Creates new form VAdmAlumnosEliminados
     */
    public VAdmDocentesEliminados() {
        initComponents();
        
        bd.abrirConexion();
        llenarTablaDeDocentes(bd.consultarDocentesEliminados());
        bd.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_docentes = new javax.swing.JTable();
        pn_buscar = new javax.swing.JPanel();
        lb_buscarPorMatricula = new javax.swing.JLabel();
        tf_buscarPorId = new javax.swing.JTextField();
        lb_buscarPorNombre = new javax.swing.JLabel();
        tf_buscarPorNombre = new javax.swing.JTextField();
        lb_buscar = new javax.swing.JLabel();
        bt_limpiarBusqueda = new javax.swing.JButton();
        bt_restaurarDocente = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pn_principal.setBackground(new java.awt.Color(255, 255, 255));
        pn_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_docentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nombre", "Contraseña", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_docentes.setName(""); // NOI18N
        tb_docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_docentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_docentes);

        pn_principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 780, 370));

        pn_buscar.setBackground(new java.awt.Color(204, 204, 204));

        lb_buscarPorMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscarPorMatricula.setText("Id del docente:");

        tf_buscarPorId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_buscarPorId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_buscarPorIdKeyPressed(evt);
            }
        });

        lb_buscarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscarPorNombre.setText("Nombre del docente:");

        tf_buscarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_buscarPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_buscarPorNombreKeyPressed(evt);
            }
        });

        lb_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_buscar.setText("Buscar");

        bt_limpiarBusqueda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_limpiarBusqueda.setText("Limpiar");
        bt_limpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_buscarLayout = new javax.swing.GroupLayout(pn_buscar);
        pn_buscar.setLayout(pn_buscarLayout);
        pn_buscarLayout.setHorizontalGroup(
            pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_buscarPorMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_buscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_buscarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lb_buscarPorNombre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_buscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_buscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_limpiarBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_buscarLayout.setVerticalGroup(
            pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_buscarPorMatricula)
                    .addComponent(lb_buscarPorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_buscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_buscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_limpiarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );

        pn_principal.add(pn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 100));

        bt_restaurarDocente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_restaurarDocente.setText("Restaurar Docente");
        bt_restaurarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_restaurarDocenteActionPerformed(evt);
            }
        });
        pn_principal.add(bt_restaurarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_docentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_docentesMouseClicked
        numFilaSeleccionada = tb_docentes.rowAtPoint(evt.getPoint());

        docente = new Docente(Integer.parseInt(tb_docentes.getValueAt(numFilaSeleccionada, 0)+""),tb_docentes.getValueAt(numFilaSeleccionada, 1)+"",tb_docentes.getValueAt(numFilaSeleccionada, 2)+"");
    }//GEN-LAST:event_tb_docentesMouseClicked

    private void tf_buscarPorIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarPorIdKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            bd.abrirConexion();
            llenarTablaDeDocentes(bd.buscarDocentesEliminados(CRITERIO_MATRICULA, tf_buscarPorId.getText()));
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_tf_buscarPorIdKeyPressed

    private void tf_buscarPorNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarPorNombreKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            bd.abrirConexion();
            llenarTablaDeDocentes(bd.buscarDocentesEliminados(CRITERIO_NOMBRE, tf_buscarPorNombre.getText()));
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_tf_buscarPorNombreKeyPressed

    private void bt_limpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarBusquedaActionPerformed
        bd.abrirConexion();
        llenarTablaDeDocentes(bd.consultarDocentesEliminados());
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_limpiarBusquedaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VAdmAdministrarDocentes interfaz = new VAdmAdministrarDocentes();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void bt_restaurarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_restaurarDocenteActionPerformed
        if (docente == null ) {
            JOptionPane.showMessageDialog(null, "Da click en un docente primero");
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea restaurar al docente " + docente.getPkId() + "?", "Confirmar Baja", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            docente.setFkEstado(Estado.Activo);
            Administrador.establecerEstadoDeUsuario(docente);
            
            bd.abrirConexion();
            llenarTablaDeDocentes(bd.consultarDocentesEliminados());
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_bt_restaurarDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmDocentesEliminados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmDocentesEliminados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmDocentesEliminados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmDocentesEliminados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmDocentesEliminados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpiarBusqueda;
    private javax.swing.JButton bt_restaurarDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_buscar;
    private javax.swing.JLabel lb_buscarPorMatricula;
    private javax.swing.JLabel lb_buscarPorNombre;
    private javax.swing.JPanel pn_buscar;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JTable tb_docentes;
    private javax.swing.JTextField tf_buscarPorId;
    private javax.swing.JTextField tf_buscarPorNombre;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaDeDocentes(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tb_docentes.getModel();
            dtm.setRowCount(0);

            if (rs != null) {
                while (rs.next()) {
                    String[] fila = {rs.getString("pkId"), rs.getString("Nombre"), rs.getString("Contrasena"), rs.getString("fkEstado")};
                    dtm.addRow(fila);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
