/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Administrador;
import Clase.Computadora;
import Clase.EstatusPc;
import Clase.Salon;
import Modelo.BaseDeDatos;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geovanni
 */
public class VAdmVerSoftwareDeUnaPc extends javax.swing.JFrame {
    private String softwareDeLaTabla;
    private String softwareDeJComboBox;
    private final Computadora computadora;
    private int numFilaSeleccionada;
    
    private static BaseDeDatos bd = new BaseDeDatos();
    
    /**
     * Creates new form VAdmVerSoftwareDeUnaPc
     */
    
    public VAdmVerSoftwareDeUnaPc(Computadora computadora) {
        initComponents();
        
        this.computadora = computadora;
        
        bd.abrirConexion();
        llenarJComboBoxDeSoftware(bd.consultarSoftware());
        llenarTablaDeSoftware(bd.consultarSoftwareDePc(computadora));
        bd.cerrarConexion();
        
        lb_titulo.setText("Software de la computadora: " + computadora.getPkId());
        softwareDeJComboBox = cb_software.getSelectedItem()+"";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_software = new javax.swing.JTable();
        bt_registrar = new javax.swing.JButton();
        cb_software = new javax.swing.JComboBox<>();
        lb_software = new javax.swing.JLabel();
        bt_eliminar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_titulo.setText("Software de la computadora: pkId");

        tb_software.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_software.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del software"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_softwareMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_software);

        bt_registrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_registrar.setText("Registrar software");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });

        cb_software.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cb_software.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_softwareActionPerformed(evt);
            }
        });

        lb_software.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lb_software.setText("Software:");

        bt_eliminar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_eliminar.setText("Eliminar software");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_registrar)
                            .addComponent(cb_software, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_software)
                            .addComponent(bt_eliminar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_software)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_software, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_eliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_softwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_softwareMouseClicked
        numFilaSeleccionada = tb_software.rowAtPoint(evt.getPoint());

        softwareDeLaTabla = tb_software.getValueAt(numFilaSeleccionada, 0)+"";
        
        cb_software.setSelectedItem(softwareDeLaTabla);
    }//GEN-LAST:event_tb_softwareMouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        Administrador.agregarSoftwareEnComputadora(computadora, softwareDeJComboBox);

        bd.abrirConexion();
        llenarTablaDeSoftware(bd.consultarSoftwareDePc(computadora));
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        Administrador.retirarSoftwareEnComputadora(computadora, softwareDeLaTabla);

        bd.abrirConexion();
        llenarTablaDeSoftware(bd.consultarSoftwareDePc(computadora));
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void cb_softwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_softwareActionPerformed
        softwareDeJComboBox = cb_software.getSelectedItem()+"";
    }//GEN-LAST:event_cb_softwareActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VAdmAdministrarInventario interfaz = new VAdmAdministrarInventario();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmVerSoftwareDeUnaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmVerSoftwareDeUnaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmVerSoftwareDeUnaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmVerSoftwareDeUnaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmVerSoftwareDeUnaPc(new Computadora(null, null, null, null, null, null, null, null, null)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cb_software;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_software;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTable tb_software;
    // End of variables declaration//GEN-END:variables

    private void llenarJComboBoxDeSoftware(ResultSet rs) {
        try {
            if (rs != null) {
                while (rs.next()) {
                    cb_software.addItem(rs.getString("Software"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: No se pudó realizar la consulta de software");
        }
    }
    
    private void llenarTablaDeSoftware(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tb_software.getModel();
            dtm.setRowCount(0);
            
            if (rs != null) {
                while (rs.next()) {
                    String[] fila = {rs.getString("Software")};
                    dtm.addRow(fila);
                }
            }
            tb_software.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: No se pudó realizar la consulta");
        }
    }
}
