/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Administrador;
import Clase.Materia;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geovanni
 */
public class VAdmAdministrarSoftware extends javax.swing.JFrame {
    private String software;
    private int numFilaSeleccionada;
    
    private BaseDeDatos bd = new BaseDeDatos();
    
    /**
     * Creates new form AdministrarMaterias
     */
    public VAdmAdministrarSoftware() {
        initComponents();
        
        bd.abrirConexion();
        llenarTablaDeSoftware(bd.consultarSoftware());
        bd.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_software = new javax.swing.JTable();
        lb_titulo = new javax.swing.JLabel();
        lb_nombreDeSoftware = new javax.swing.JLabel();
        tf_nombreDeSoftware = new javax.swing.JTextField();
        bt_eliminar = new javax.swing.JButton();
        bt_registrar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tb_software.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_software.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_softwareMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_software);

        lb_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_titulo.setText("Administración de software");

        lb_nombreDeSoftware.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_nombreDeSoftware.setText("Nombre del software:");

        tf_nombreDeSoftware.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bt_eliminar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        bt_registrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_titulo)
                    .addComponent(lb_nombreDeSoftware)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_nombreDeSoftware, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_registrar)
                        .addGap(121, 121, 121)
                        .addComponent(bt_eliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nombreDeSoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombreDeSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrar)
                    .addComponent(bt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        if (nombreEstaVacio()) return;
        
        software = tf_nombreDeSoftware.getText();
        
        Administrador.registrarSoftware(software);
        
        bd.abrirConexion();
        llenarTablaDeSoftware(bd.consultarSoftware());
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        if (nombreEstaVacio()) return;
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el software " + software + "?", "Confirmar Baja", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            software = tf_nombreDeSoftware.getText();
            
            Administrador.eliminarSoftware(software);

            bd.abrirConexion();
            llenarTablaDeSoftware(bd.consultarSoftware());
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void tb_softwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_softwareMouseClicked
        numFilaSeleccionada = tb_software.rowAtPoint(evt.getPoint());
        
        software = tb_software.getValueAt(numFilaSeleccionada, 0)+"";

        tf_nombreDeSoftware.setText(software);
    }//GEN-LAST:event_tb_softwareMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VAdmAdministrarInventario interfaz = new VAdmAdministrarInventario();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmAdministrarSoftware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_nombreDeSoftware;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTable tb_software;
    private javax.swing.JTextField tf_nombreDeSoftware;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaDeSoftware(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tb_software.getModel();
            dtm.setRowCount(0);
            
            if (rs != null) {
                while (rs.next()) {
                    String[] fila = {rs.getString("Software")};
                    dtm.addRow(fila);
                }
            }
            tb_software.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: No se pudó realizar la consulta");
        }
    }
    
    private boolean nombreEstaVacio() {
        if (tf_nombreDeSoftware.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre del software esta vacío");
            return true;
        } else {
            return false;
        }
    }
}
