/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Administrador;
import Clase.Alumno;
import Clase.Estado;
import Clase.Estatus;
import Clase.TipoDeUsuario;
import Clase.Usuario;
import Modelo.BaseDeDatos;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import interfas_alumno.Inventario;
import interfas_alumno.Reportes;
import interfas_alumno.Rondines;
import interfas_alumno.Notificaciones;
import interfas_alumno.Usuarios;
/**
 *
 * @author Geovanni
 */
public class VAdmAdministrarAlumnos extends javax.swing.JFrame {
    private Alumno alumno;
    private int numFilaSeleccionada;
    
    private final String CRITERIO_MATRICULA = "pkId";
    private final String CRITERIO_NOMBRE = "Nombre";
    
    private BaseDeDatos bd = new BaseDeDatos();
    
    /**
     * Creates new form AdministrarLas
     */
    public VAdmAdministrarAlumnos() {
        initComponents();
        
        bd.abrirConexion();
        llenarTablaDeAlumnos(bd.consultarAlumnos());
        bd.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alumnos = new javax.swing.JTable();
        pn_administracion = new javax.swing.JPanel();
        lb_matriculaDelAlumno = new javax.swing.JLabel();
        tf_matriculaDelAlumno = new javax.swing.JTextField();
        lb_nombreDelAlumno = new javax.swing.JLabel();
        tf_nombreDelAlumno = new javax.swing.JTextField();
        lb_contrasena = new javax.swing.JLabel();
        tf_contrasena = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_suspender = new javax.swing.JButton();
        lb_administracion = new javax.swing.JLabel();
        bt_eliminar = new javax.swing.JButton();
        bt_quitarSuspension = new javax.swing.JButton();
        pn_buscar = new javax.swing.JPanel();
        lb_buscarPorMatricula = new javax.swing.JLabel();
        tf_buscarPorMatricula = new javax.swing.JTextField();
        lb_buscarPorNombre = new javax.swing.JLabel();
        tf_buscarPorNombre = new javax.swing.JTextField();
        lb_buscar = new javax.swing.JLabel();
        pn_ordenarPor = new javax.swing.JPanel();
        lb_ordenarPor = new javax.swing.JLabel();
        bt_ordenarPorMatricula = new javax.swing.JButton();
        bt_ordenarPorNombre = new javax.swing.JButton();
        pn_mostrarAlumnosEliminados = new javax.swing.JPanel();
        bt_mostrarAlumnosEliminados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pn_alumnos = new javax.swing.JPanel();
        lb_alumnos = new javax.swing.JLabel();
        pn_maestros = new javax.swing.JPanel();
        lb_maestros = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_administrarHorarios = new javax.swing.JToggleButton();
        bt_inventario2 = new javax.swing.JToggleButton();
        bt_reportes = new javax.swing.JButton();
        bt_rondines = new javax.swing.JButton();
        bt_notificaciones = new javax.swing.JButton();
        bt_inventario1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1066, 692));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_alumnos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nombre", "Contraseña", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_alumnos.setName(""); // NOI18N
        tb_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_alumnos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 720, 720));

        pn_administracion.setBackground(new java.awt.Color(204, 204, 204));

        lb_matriculaDelAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_matriculaDelAlumno.setText("Matrícula del alumno:");

        tf_matriculaDelAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lb_nombreDelAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_nombreDelAlumno.setText("Nombre del alumno:");

        tf_nombreDelAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lb_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_contrasena.setText("Contraseña:");

        tf_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bt_registrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_registrar.setText("Registrar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_modificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_suspender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_suspender.setText("Suspender alumno");
        bt_suspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suspenderActionPerformed(evt);
            }
        });

        lb_administracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_administracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_administracion.setText("Administración");

        bt_eliminar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_quitarSuspension.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_quitarSuspension.setText("Quitar suspensión");
        bt_quitarSuspension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitarSuspensionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_administracionLayout = new javax.swing.GroupLayout(pn_administracion);
        pn_administracion.setLayout(pn_administracionLayout);
        pn_administracionLayout.setHorizontalGroup(
            pn_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_administracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_matriculaDelAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_matriculaDelAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_nombreDelAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_nombreDelAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_registrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_administracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(bt_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(bt_suspender, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addComponent(bt_quitarSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_administracionLayout.setVerticalGroup(
            pn_administracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_administracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_administracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_matriculaDelAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_matriculaDelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nombreDelAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombreDelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_contrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(bt_suspender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_quitarSuspension)
                .addContainerGap())
        );

        jPanel3.add(pn_administracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 440));

        pn_buscar.setBackground(new java.awt.Color(204, 204, 204));

        lb_buscarPorMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscarPorMatricula.setText("Matrícula del alumno:");

        tf_buscarPorMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_buscarPorMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_buscarPorMatriculaKeyPressed(evt);
            }
        });

        lb_buscarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscarPorNombre.setText("Nombre del alumno:");

        tf_buscarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_buscarPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_buscarPorNombreKeyPressed(evt);
            }
        });

        lb_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_buscar.setText("Buscar");

        javax.swing.GroupLayout pn_buscarLayout = new javax.swing.GroupLayout(pn_buscar);
        pn_buscar.setLayout(pn_buscarLayout);
        pn_buscarLayout.setHorizontalGroup(
            pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_buscarPorMatricula)
                    .addComponent(tf_buscarPorMatricula)
                    .addComponent(lb_buscarPorNombre)
                    .addComponent(tf_buscarPorNombre)
                    .addComponent(lb_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_buscarLayout.setVerticalGroup(
            pn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_buscarPorMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_buscarPorMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_buscarPorNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_buscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        jPanel3.add(pn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 280, 170));

        pn_ordenarPor.setBackground(new java.awt.Color(153, 153, 153));
        pn_ordenarPor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_ordenarPor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ordenarPor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ordenarPor.setText("Ordenar por");
        pn_ordenarPor.add(lb_ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        bt_ordenarPorMatricula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_ordenarPorMatricula.setText("Matrícula");
        bt_ordenarPorMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ordenarPorMatriculaActionPerformed(evt);
            }
        });
        pn_ordenarPor.add(bt_ordenarPorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        bt_ordenarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_ordenarPorNombre.setText("Nombre");
        bt_ordenarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ordenarPorNombreActionPerformed(evt);
            }
        });
        pn_ordenarPor.add(bt_ordenarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 130, -1));

        jPanel3.add(pn_ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 80));

        pn_mostrarAlumnosEliminados.setBackground(new java.awt.Color(153, 153, 153));

        bt_mostrarAlumnosEliminados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_mostrarAlumnosEliminados.setText("Mostrar alumnos eliminados");
        bt_mostrarAlumnosEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostrarAlumnosEliminadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mostrarAlumnosEliminadosLayout = new javax.swing.GroupLayout(pn_mostrarAlumnosEliminados);
        pn_mostrarAlumnosEliminados.setLayout(pn_mostrarAlumnosEliminadosLayout);
        pn_mostrarAlumnosEliminadosLayout.setHorizontalGroup(
            pn_mostrarAlumnosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mostrarAlumnosEliminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_mostrarAlumnosEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_mostrarAlumnosEliminadosLayout.setVerticalGroup(
            pn_mostrarAlumnosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mostrarAlumnosEliminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_mostrarAlumnosEliminados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(pn_mostrarAlumnosEliminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 280, 50));

        jPanel2.setBackground(new java.awt.Color(255, 198, 38));

        pn_alumnos.setBackground(new java.awt.Color(255, 255, 255));

        lb_alumnos.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_alumnos.setText("Alumnos");

        javax.swing.GroupLayout pn_alumnosLayout = new javax.swing.GroupLayout(pn_alumnos);
        pn_alumnos.setLayout(pn_alumnosLayout);
        pn_alumnosLayout.setHorizontalGroup(
            pn_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_alumnosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_alumnos)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pn_alumnosLayout.setVerticalGroup(
            pn_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_alumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_alumnos)
                .addContainerGap())
        );

        pn_maestros.setBackground(new java.awt.Color(101, 0, 11));
        pn_maestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_maestrosMouseClicked(evt);
            }
        });

        lb_maestros.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_maestros.setForeground(new java.awt.Color(255, 255, 255));
        lb_maestros.setText("Maestros");

        javax.swing.GroupLayout pn_maestrosLayout = new javax.swing.GroupLayout(pn_maestros);
        pn_maestros.setLayout(pn_maestrosLayout);
        pn_maestrosLayout.setHorizontalGroup(
            pn_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_maestrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_maestros)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pn_maestrosLayout.setVerticalGroup(
            pn_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_maestrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_maestros, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_maestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_alumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_maestros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(1, 26, 93));

        bt_administrarHorarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administrarHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario60X60.png"))); // NOI18N
        bt_administrarHorarios.setText("Administrar horarios");
        bt_administrarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarHorariosActionPerformed(evt);
            }
        });

        bt_inventario2.setBackground(new java.awt.Color(204, 204, 204));
        bt_inventario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_inventario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo-de-usuarios60X60.png"))); // NOI18N
        bt_inventario2.setText("    Usuarios");
        bt_inventario2.setBorder(null);
        bt_inventario2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_inventario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inventario2ActionPerformed(evt);
            }
        });

        bt_reportes.setBackground(new java.awt.Color(204, 204, 204));
        bt_reportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte2_60X60.png"))); // NOI18N
        bt_reportes.setText("Reportes                     ");
        bt_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportesActionPerformed(evt);
            }
        });

        bt_rondines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_rondines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ronda60X60.png"))); // NOI18N
        bt_rondines.setText("Rondines              ");
        bt_rondines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rondinesActionPerformed(evt);
            }
        });

        bt_notificaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_notificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correo60X60.png"))); // NOI18N
        bt_notificaciones.setText("Notificaciones         ");
        bt_notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_notificacionesActionPerformed(evt);
            }
        });

        bt_inventario1.setBackground(new java.awt.Color(204, 204, 204));
        bt_inventario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_inventario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario60X60.png"))); // NOI18N
        bt_inventario1.setText(" Inventario           ");
        bt_inventario1.setBorder(null);
        bt_inventario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_inventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inventario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_inventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_notificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_inventario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_administrarHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_rondines, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_administrarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_inventario2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(bt_rondines, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_inventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_alumnosMouseClicked
        numFilaSeleccionada = tb_alumnos.rowAtPoint(evt.getPoint());

        alumno = new Alumno(Integer.parseInt(tb_alumnos.getValueAt(numFilaSeleccionada, 0)+""),tb_alumnos.getValueAt(numFilaSeleccionada, 1)+"",tb_alumnos.getValueAt(numFilaSeleccionada, 2)+"", Estatus.valueOf(tb_alumnos.getValueAt(numFilaSeleccionada, 3)+""));
        
        tf_matriculaDelAlumno.setText(alumno.getPkId()+"");
        tf_nombreDelAlumno.setText(alumno.getNombre());
        tf_contrasena.setText(alumno.getContrasena());
    }//GEN-LAST:event_tb_alumnosMouseClicked

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        if (camposEstanVacios()) return;

        Usuario alumnoNuevo = new Alumno(Integer.parseInt(tf_matriculaDelAlumno.getText()), tf_nombreDelAlumno.getText(), tf_contrasena.getText(), Estatus.Activo);
        
        Administrador.registrarUsuario(alumnoNuevo);
        
        bd.abrirConexion();
        llenarTablaDeAlumnos(bd.consultarAlumnos());
        bd.cerrarConexion();
        limpiarCampos();
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        if (camposEstanVacios()) return;
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea confirmar los siguientes cambios para el alumno " + alumno.getPkId() + "?:\nNombre:\n   " + alumno.getNombre() + " -> " + tf_nombreDelAlumno.getText() + "\nContraseña:\n   " + alumno.getContrasena() + " -> " + tf_contrasena.getText(), "Confirmar cambios", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            // La matrícula (Id) no se puede modificar, por ello se obtiene del alumno creado a partir del mouse clicked
            alumno.setNombre(tf_nombreDelAlumno.getText());
            alumno.setContrasena(tf_contrasena.getText());

            Administrador.modificarUsuario(alumno);

            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.consultarAlumnos());
            bd.cerrarConexion();
            limpiarCampos();
        }
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (tf_matriculaDelAlumno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una matrícula para poder dar de baja");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar al alumno " + alumno.getPkId() + "?", "Confirmar Baja", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            alumno.setFkEstado(Estado.Eliminado);
            Administrador.establecerEstadoDeUsuario(alumno);
            
            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.consultarAlumnos());
            bd.cerrarConexion();
            limpiarCampos();
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_suspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suspenderActionPerformed
        if (camposEstanVacios()) return;
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea suspender al alumno " + alumno.getPkId() + "?", "Confirmar Baja", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            alumno.setFkEstatus(Estatus.Inactivo);
            Administrador.establecerEstatusDeUsuario(alumno);

            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.consultarAlumnos());
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_bt_suspenderActionPerformed

    private void bt_mostrarAlumnosEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostrarAlumnosEliminadosActionPerformed
        VAdmAlumnosEliminados interfaz = new VAdmAlumnosEliminados();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_mostrarAlumnosEliminadosActionPerformed

    private void pn_maestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_maestrosMouseClicked
        VAdmAdministrarDocentes interfaz = new VAdmAdministrarDocentes();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pn_maestrosMouseClicked

    private void tf_buscarPorNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarPorNombreKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.buscarAlumnos(CRITERIO_NOMBRE, tf_buscarPorNombre.getText()));
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_tf_buscarPorNombreKeyPressed

    private void tf_buscarPorMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarPorMatriculaKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.buscarAlumnos(CRITERIO_MATRICULA, tf_buscarPorMatricula.getText()));
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_tf_buscarPorMatriculaKeyPressed

    private void bt_quitarSuspensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitarSuspensionActionPerformed
        if (camposEstanVacios()) return;
        
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea retirar la suspensión al alumno " + alumno.getPkId() + "?", "Confirmar Baja", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            alumno.setFkEstatus(Estatus.Activo);
            Administrador.establecerEstatusDeUsuario(alumno);

            bd.abrirConexion();
            llenarTablaDeAlumnos(bd.consultarAlumnos());
            bd.cerrarConexion();
        }
    }//GEN-LAST:event_bt_quitarSuspensionActionPerformed

    private void bt_ordenarPorMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ordenarPorMatriculaActionPerformed
        bd.abrirConexion();
        llenarTablaDeAlumnos(bd.consultarAlumnosPorMatricula());
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_ordenarPorMatriculaActionPerformed

    private void bt_ordenarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ordenarPorNombreActionPerformed
        bd.abrirConexion();
        llenarTablaDeAlumnos(bd.consultarAlumnosPorNombre());
        bd.cerrarConexion();
    }//GEN-LAST:event_bt_ordenarPorNombreActionPerformed

    private void bt_administrarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarHorariosActionPerformed
        VAdmAdministrarHorarios ventana = new VAdmAdministrarHorarios();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_administrarHorariosActionPerformed

    private void bt_inventario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inventario2ActionPerformed
        VAdmAdministrarAlumnos ventana = new VAdmAdministrarAlumnos();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_inventario2ActionPerformed

    private void bt_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportesActionPerformed
        Reportes ventana = new Reportes("");
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_reportesActionPerformed

    private void bt_rondinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rondinesActionPerformed
        Rondines ventana = new Rondines("");
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_rondinesActionPerformed

    private void bt_notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_notificacionesActionPerformed
        Notificaciones ventana = new Notificaciones("");
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_notificacionesActionPerformed

    private void bt_inventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inventario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_inventario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmAdministrarAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_administrarHorarios;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JToggleButton bt_inventario1;
    private javax.swing.JToggleButton bt_inventario2;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_mostrarAlumnosEliminados;
    private javax.swing.JButton bt_notificaciones;
    private javax.swing.JButton bt_ordenarPorMatricula;
    private javax.swing.JButton bt_ordenarPorNombre;
    private javax.swing.JButton bt_quitarSuspension;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_reportes;
    private javax.swing.JButton bt_rondines;
    private javax.swing.JButton bt_suspender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_administracion;
    private javax.swing.JLabel lb_alumnos;
    private javax.swing.JLabel lb_buscar;
    private javax.swing.JLabel lb_buscarPorMatricula;
    private javax.swing.JLabel lb_buscarPorNombre;
    private javax.swing.JLabel lb_contrasena;
    private javax.swing.JLabel lb_maestros;
    private javax.swing.JLabel lb_matriculaDelAlumno;
    private javax.swing.JLabel lb_nombreDelAlumno;
    private javax.swing.JLabel lb_ordenarPor;
    private javax.swing.JPanel pn_administracion;
    private javax.swing.JPanel pn_alumnos;
    private javax.swing.JPanel pn_buscar;
    private javax.swing.JPanel pn_maestros;
    private javax.swing.JPanel pn_mostrarAlumnosEliminados;
    private javax.swing.JPanel pn_ordenarPor;
    private javax.swing.JTable tb_alumnos;
    private javax.swing.JTextField tf_buscarPorMatricula;
    private javax.swing.JTextField tf_buscarPorNombre;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_matriculaDelAlumno;
    private javax.swing.JTextField tf_nombreDelAlumno;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaDeAlumnos(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tb_alumnos.getModel();
            dtm.setRowCount(0);

            if (rs != null) {
                while (rs.next()) {
                    String[] fila = {rs.getString("pkId"), rs.getString("Nombre"), rs.getString("Contrasena"), rs.getString("fkEstatus")};
                    dtm.addRow(fila);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void limpiarCampos() {
        tf_nombreDelAlumno.setText("");
        tf_matriculaDelAlumno.setText("");
        tf_contrasena.setText("");
    }
    
    private boolean camposEstanVacios() {
        if (tf_nombreDelAlumno.getText().isEmpty() || tf_matriculaDelAlumno.getText().isEmpty() || tf_contrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben llenarse");
            return true;
        } else {
            return false;
        }
    }
}
