/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Administrador;
import Clase.Componente;
import Clase.Computadora;
import Clase.EstatusPc;
import Clase.Salon;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geovanni
 */
public class VAdmAdministrarInventario extends javax.swing.JFrame {
    private Computadora computadora;
    private int numFilaSeleccionada;
    private static Salon salon = Salon.LAS;
    
    private BaseDeDatos bd = new BaseDeDatos();
    
    private static final Color COLOR_VINO = new Color(101,0,11);
    
    /**
     * Creates new form AdministrarLas
     */
    public VAdmAdministrarInventario() {
        initComponents();
        
        tb_computadoras.getColumnModel().getColumn(0).setPreferredWidth(10);
        tb_computadoras.getColumnModel().getColumn(1).setPreferredWidth(30);
        tb_computadoras.getColumnModel().getColumn(3).setPreferredWidth(20);
        tb_computadoras.getColumnModel().getColumn(5).setPreferredWidth(20);
        tb_computadoras.getColumnModel().getColumn(7).setPreferredWidth(20);
        tb_computadoras.getColumnModel().getColumn(9).setPreferredWidth(20);
        tb_computadoras.getColumnModel().getColumn(11).setPreferredWidth(20);
        tb_computadoras.getColumnModel().getColumn(13).setPreferredWidth(20);
        
        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb_computadora = new javax.swing.JLabel();
        lb_idComputador = new javax.swing.JLabel();
        lb_mouseDescripcion = new javax.swing.JLabel();
        tf_mouseDescripcion = new javax.swing.JTextField();
        tf_mouseNumSerie = new javax.swing.JTextField();
        lb_mouseNumSerie = new javax.swing.JLabel();
        lb_mouse = new javax.swing.JLabel();
        lb_teclado = new javax.swing.JLabel();
        lb_tecladoDescripcion = new javax.swing.JLabel();
        tf_tecladoDescripcion = new javax.swing.JTextField();
        lb_tecladoNumSerie = new javax.swing.JLabel();
        tf_tecladoNumSerie = new javax.swing.JTextField();
        lb_monitor = new javax.swing.JLabel();
        lb_monitorDescripcion = new javax.swing.JLabel();
        tf_monitorDescripcion = new javax.swing.JTextField();
        lb_monitorNumSerie = new javax.swing.JLabel();
        tf_monitorNumSerie = new javax.swing.JTextField();
        lb_procesador = new javax.swing.JLabel();
        lb_procesadorDescripcion = new javax.swing.JLabel();
        tf_procesadorDescripcion = new javax.swing.JTextField();
        lb_procesadorNumSerie = new javax.swing.JLabel();
        tf_procesadorNumSerie = new javax.swing.JTextField();
        lb_ram = new javax.swing.JLabel();
        lb_ramDescripcion = new javax.swing.JLabel();
        tf_ramDescripcion = new javax.swing.JTextField();
        lb_ramNumSerie = new javax.swing.JLabel();
        tf_ramNumSerie = new javax.swing.JTextField();
        lb_almacenamiento = new javax.swing.JLabel();
        lb_almacenamientoDescripcion = new javax.swing.JLabel();
        tf_almacenamientoDescripcion = new javax.swing.JTextField();
        lb_almacenamientoNumSerie = new javax.swing.JLabel();
        tf_almacenamientoNumSerie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_computadoras = new javax.swing.JTable();
        bt_modificar = new javax.swing.JButton();
        bt_administrarSoftware = new javax.swing.JButton();
        bt_verSoftware = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        pn_Las1 = new javax.swing.JPanel();
        lb_Las1 = new javax.swing.JLabel();
        pn_Ldm = new javax.swing.JPanel();
        lb_Ldm = new javax.swing.JLabel();
        pn_Lds = new javax.swing.JPanel();
        lb_Lds = new javax.swing.JLabel();
        pn_Lpg = new javax.swing.JPanel();
        lb_Lpg = new javax.swing.JLabel();
        pn_Lso = new javax.swing.JPanel();
        lb_Lso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 26, 93));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        jLabel2.setText("Administras horarios");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jLabel3.setText("Administrar usuarios");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        jLabel4.setText("Reportes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rondin.png"))); // NOI18N
        jLabel5.setText("Rondines");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notificacion.png"))); // NOI18N
        jLabel6.setText("Notificaciones");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.png"))); // NOI18N
        jLabel7.setText("Inventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1066, 692));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_computadora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_computadora.setText("Computadora");
        jPanel3.add(lb_computadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lb_idComputador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_idComputador.setText("pkId");
        jPanel3.add(lb_idComputador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lb_mouseDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_mouseDescripcion.setText("Descripción");
        jPanel3.add(lb_mouseDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        tf_mouseDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_mouseDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, -1));

        tf_mouseNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_mouseNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, -1));

        lb_mouseNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_mouseNumSerie.setText("Número de serie");
        jPanel3.add(lb_mouseNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, -1));

        lb_mouse.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_mouse.setText("Mouse");
        jPanel3.add(lb_mouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lb_teclado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_teclado.setText("Teclado");
        jPanel3.add(lb_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        lb_tecladoDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_tecladoDescripcion.setText("Descripción");
        jPanel3.add(lb_tecladoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        tf_tecladoDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_tecladoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 240, -1));

        lb_tecladoNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_tecladoNumSerie.setText("Número de serie");
        jPanel3.add(lb_tecladoNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        tf_tecladoNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_tecladoNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 160, -1));

        lb_monitor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_monitor.setText("Monitor");
        jPanel3.add(lb_monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        lb_monitorDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_monitorDescripcion.setText("Descripción");
        jPanel3.add(lb_monitorDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        tf_monitorDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_monitorDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 240, -1));

        lb_monitorNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_monitorNumSerie.setText("Número de serie");
        jPanel3.add(lb_monitorNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, -1, -1));

        tf_monitorNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_monitorNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 110, 160, -1));

        lb_procesador.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_procesador.setText("Procesador");
        jPanel3.add(lb_procesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lb_procesadorDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_procesadorDescripcion.setText("Descripción");
        jPanel3.add(lb_procesadorDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        tf_procesadorDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_procesadorDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));

        lb_procesadorNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_procesadorNumSerie.setText("Número de serie");
        jPanel3.add(lb_procesadorNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        tf_procesadorNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_procesadorNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 160, -1));

        lb_ram.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_ram.setText("RAM");
        jPanel3.add(lb_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        lb_ramDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ramDescripcion.setText("Descripción");
        jPanel3.add(lb_ramDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        tf_ramDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_ramDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 240, -1));

        lb_ramNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ramNumSerie.setText("Número de serie");
        jPanel3.add(lb_ramNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        tf_ramNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_ramNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 160, -1));

        lb_almacenamiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lb_almacenamiento.setText("Almacenamiento");
        jPanel3.add(lb_almacenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, -1, -1));

        lb_almacenamientoDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_almacenamientoDescripcion.setText("Descripción");
        jPanel3.add(lb_almacenamientoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, -1, -1));

        tf_almacenamientoDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_almacenamientoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 240, -1));

        lb_almacenamientoNumSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_almacenamientoNumSerie.setText("Número de serie");
        jPanel3.add(lb_almacenamientoNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, -1, -1));

        tf_almacenamientoNumSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(tf_almacenamientoNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 160, -1));

        tb_computadoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_computadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Estatus", "Mouse", "MouseNumSerie", "Teclado", "TecladoNumSerie", "Monitor", "MonitorNumSerie", "Procesador", "ProcesadorNumSerie", "Ram", "RamNumSerie", "Almacenamiento", "AlmacenamientoNumSerie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_computadoras.setName(""); // NOI18N
        tb_computadoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_computadorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_computadoras);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1250, 450));

        bt_modificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });
        jPanel3.add(bt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, 280, -1));

        bt_administrarSoftware.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_administrarSoftware.setText("Administrar software");
        bt_administrarSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarSoftwareActionPerformed(evt);
            }
        });
        jPanel3.add(bt_administrarSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 700, 280, -1));

        bt_verSoftware.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_verSoftware.setText("Ver software instalado");
        bt_verSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verSoftwareActionPerformed(evt);
            }
        });
        jPanel3.add(bt_verSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 280, -1));

        jPanel8.setBackground(new java.awt.Color(255, 198, 38));

        pn_Las1.setBackground(new java.awt.Color(255, 255, 255));
        pn_Las1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_Las1MouseClicked(evt);
            }
        });

        lb_Las1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_Las1.setText("LAS");

        javax.swing.GroupLayout pn_Las1Layout = new javax.swing.GroupLayout(pn_Las1);
        pn_Las1.setLayout(pn_Las1Layout);
        pn_Las1Layout.setHorizontalGroup(
            pn_Las1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Las1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_Las1)
                .addGap(41, 41, 41))
        );
        pn_Las1Layout.setVerticalGroup(
            pn_Las1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Las1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Las1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_Ldm.setBackground(new java.awt.Color(101, 0, 11));
        pn_Ldm.setForeground(new java.awt.Color(255, 255, 255));
        pn_Ldm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LdmMouseClicked(evt);
            }
        });

        lb_Ldm.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_Ldm.setForeground(new java.awt.Color(255, 255, 255));
        lb_Ldm.setText("LDM");

        javax.swing.GroupLayout pn_LdmLayout = new javax.swing.GroupLayout(pn_Ldm);
        pn_Ldm.setLayout(pn_LdmLayout);
        pn_LdmLayout.setHorizontalGroup(
            pn_LdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LdmLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_Ldm)
                .addGap(41, 41, 41))
        );
        pn_LdmLayout.setVerticalGroup(
            pn_LdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LdmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Ldm)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_Lds.setBackground(new java.awt.Color(101, 0, 11));
        pn_Lds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LdsMouseClicked(evt);
            }
        });

        lb_Lds.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_Lds.setForeground(new java.awt.Color(255, 255, 255));
        lb_Lds.setText("LDS");

        javax.swing.GroupLayout pn_LdsLayout = new javax.swing.GroupLayout(pn_Lds);
        pn_Lds.setLayout(pn_LdsLayout);
        pn_LdsLayout.setHorizontalGroup(
            pn_LdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LdsLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_Lds)
                .addGap(41, 41, 41))
        );
        pn_LdsLayout.setVerticalGroup(
            pn_LdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LdsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Lds)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_Lpg.setBackground(new java.awt.Color(101, 0, 11));
        pn_Lpg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LpgMouseClicked(evt);
            }
        });

        lb_Lpg.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_Lpg.setForeground(new java.awt.Color(255, 255, 255));
        lb_Lpg.setText("LPG");

        javax.swing.GroupLayout pn_LpgLayout = new javax.swing.GroupLayout(pn_Lpg);
        pn_Lpg.setLayout(pn_LpgLayout);
        pn_LpgLayout.setHorizontalGroup(
            pn_LpgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LpgLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_Lpg)
                .addGap(41, 41, 41))
        );
        pn_LpgLayout.setVerticalGroup(
            pn_LpgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LpgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Lpg)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pn_Lso.setBackground(new java.awt.Color(101, 0, 11));
        pn_Lso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LsoMouseClicked(evt);
            }
        });

        lb_Lso.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lb_Lso.setForeground(new java.awt.Color(255, 255, 255));
        lb_Lso.setText("LSO");

        javax.swing.GroupLayout pn_LsoLayout = new javax.swing.GroupLayout(pn_Lso);
        pn_Lso.setLayout(pn_LsoLayout);
        pn_LsoLayout.setHorizontalGroup(
            pn_LsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LsoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lb_Lso)
                .addGap(41, 41, 41))
        );
        pn_LsoLayout.setVerticalGroup(
            pn_LsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LsoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Lso)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_Las1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Ldm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Lds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Lpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Lso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_Las1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Ldm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Lds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Lpg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Lso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_computadorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_computadorasMouseClicked
        numFilaSeleccionada = tb_computadoras.rowAtPoint(evt.getPoint());
        
        String pkId = tb_computadoras.getValueAt(numFilaSeleccionada, 0)+"";
        EstatusPc estatus = EstatusPc.valueOf(tb_computadoras.getValueAt(numFilaSeleccionada, 1)+"");
        Componente mouse = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 2)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 3)+"");
        Componente teclado = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 4)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 5)+"");
        Componente monitor = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 6)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 7)+"");
        Componente procesador = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 8)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 9)+"");
        Componente ram = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 10)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 11)+"");
        Componente almacenamiento = new Componente(tb_computadoras.getValueAt(numFilaSeleccionada, 12)+"", tb_computadoras.getValueAt(numFilaSeleccionada, 13)+"");

        computadora = new Computadora(pkId, salon, estatus, mouse, teclado, monitor, procesador, ram, almacenamiento);

        lb_idComputador.setText(pkId);
        tf_mouseDescripcion.setText(mouse.getDescripcion());
        tf_mouseNumSerie.setText(mouse.getNumSerie());
        tf_tecladoDescripcion.setText(teclado.getDescripcion());
        tf_tecladoNumSerie.setText(teclado.getNumSerie());
        tf_monitorDescripcion.setText(monitor.getDescripcion());
        tf_monitorNumSerie.setText(monitor.getNumSerie());
        tf_procesadorDescripcion.setText(procesador.getDescripcion());
        tf_procesadorNumSerie.setText(procesador.getNumSerie());
        tf_ramDescripcion.setText(ram.getDescripcion());
        tf_ramNumSerie.setText(ram.getNumSerie());
        tf_almacenamientoDescripcion.setText(almacenamiento.getDescripcion());
        tf_almacenamientoNumSerie.setText(almacenamiento.getNumSerie());
    }//GEN-LAST:event_tb_computadorasMouseClicked

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea modificar las características de la PC: " + computadora.getPkId() + "?", "Confirmar cambios", JOptionPane.OK_CANCEL_OPTION);

        if (confirmacion == 0) {
            Componente mouse = new Componente(tf_mouseDescripcion.getText(), tf_mouseNumSerie.getText());
            Componente teclado = new Componente(tf_tecladoDescripcion.getText(), tf_tecladoNumSerie.getText());
            Componente monitor = new Componente(tf_monitorDescripcion.getText(), tf_monitorNumSerie.getText());
            Componente procesador = new Componente(tf_procesadorDescripcion.getText(), tf_procesadorNumSerie.getText());
            Componente ram = new Componente(tf_ramDescripcion.getText(), tf_ramNumSerie.getText());
            Componente almacenamiento = new Componente(tf_almacenamientoDescripcion.getText(), tf_almacenamientoNumSerie.getText());

            computadora.setMouse(mouse);
            computadora.setTeclado(teclado);
            computadora.setMonitor(monitor);
            computadora.setProcesador(procesador);
            computadora.setRam(ram);
            computadora.setAlmacenamiento(almacenamiento);

            Administrador.modificarComputadora(computadora);

            bd.abrirConexion();
            llenarTablaDeComputadoras(bd.consultarInventario(salon));
            bd.cerrarConexion();
            //limpiarCampos();
        }
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void pn_LdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LdmMouseClicked
        ponerPanelesDeSalonesEnVino();
        pn_Ldm.setBackground(Color.WHITE);
        lb_Ldm.setForeground(Color.BLACK);

        salon = Salon.LDM;

        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }//GEN-LAST:event_pn_LdmMouseClicked

    private void pn_LdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LdsMouseClicked
        ponerPanelesDeSalonesEnVino();
        pn_Lds.setBackground(Color.WHITE);
        lb_Lds.setForeground(Color.BLACK);

        salon = Salon.LDS;

        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }//GEN-LAST:event_pn_LdsMouseClicked

    private void pn_LpgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpgMouseClicked
        ponerPanelesDeSalonesEnVino();
        pn_Lpg.setBackground(Color.WHITE);
        lb_Lpg.setForeground(Color.BLACK);

        salon = Salon.LPG;

        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }//GEN-LAST:event_pn_LpgMouseClicked

    private void pn_LsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LsoMouseClicked
        ponerPanelesDeSalonesEnVino();
        pn_Lso.setBackground(Color.WHITE);
        lb_Lso.setForeground(Color.BLACK);

        salon = Salon.LSO;

        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }//GEN-LAST:event_pn_LsoMouseClicked

    private void pn_Las1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_Las1MouseClicked
        ponerPanelesDeSalonesEnVino();
        pn_Las1.setBackground(Color.WHITE);
        lb_Las1.setForeground(Color.BLACK);

        salon = Salon.LAS;

        bd.abrirConexion();
        llenarTablaDeComputadoras(bd.consultarInventario(salon));
        bd.cerrarConexion();
    }//GEN-LAST:event_pn_Las1MouseClicked

    private void bt_administrarSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarSoftwareActionPerformed
        VAdmAdministrarSoftware interfaz = new VAdmAdministrarSoftware();
        this.setVisible(false);
        interfaz.setVisible(true);
    }//GEN-LAST:event_bt_administrarSoftwareActionPerformed

    private void bt_verSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verSoftwareActionPerformed
        VAdmVerSoftwareDeUnaPc interfaz = new VAdmVerSoftwareDeUnaPc(computadora);
        this.setVisible(false);
        interfaz.setVisible(true);
    }//GEN-LAST:event_bt_verSoftwareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmAdministrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmAdministrarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_administrarSoftware;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_verSoftware;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Las1;
    private javax.swing.JLabel lb_Ldm;
    private javax.swing.JLabel lb_Lds;
    private javax.swing.JLabel lb_Lpg;
    private javax.swing.JLabel lb_Lso;
    private javax.swing.JLabel lb_almacenamiento;
    private javax.swing.JLabel lb_almacenamientoDescripcion;
    private javax.swing.JLabel lb_almacenamientoNumSerie;
    private javax.swing.JLabel lb_computadora;
    private javax.swing.JLabel lb_idComputador;
    private javax.swing.JLabel lb_monitor;
    private javax.swing.JLabel lb_monitorDescripcion;
    private javax.swing.JLabel lb_monitorNumSerie;
    private javax.swing.JLabel lb_mouse;
    private javax.swing.JLabel lb_mouseDescripcion;
    private javax.swing.JLabel lb_mouseNumSerie;
    private javax.swing.JLabel lb_procesador;
    private javax.swing.JLabel lb_procesadorDescripcion;
    private javax.swing.JLabel lb_procesadorNumSerie;
    private javax.swing.JLabel lb_ram;
    private javax.swing.JLabel lb_ramDescripcion;
    private javax.swing.JLabel lb_ramNumSerie;
    private javax.swing.JLabel lb_teclado;
    private javax.swing.JLabel lb_tecladoDescripcion;
    private javax.swing.JLabel lb_tecladoNumSerie;
    private javax.swing.JPanel pn_Las1;
    private javax.swing.JPanel pn_Ldm;
    private javax.swing.JPanel pn_Lds;
    private javax.swing.JPanel pn_Lpg;
    private javax.swing.JPanel pn_Lso;
    private javax.swing.JTable tb_computadoras;
    private javax.swing.JTextField tf_almacenamientoDescripcion;
    private javax.swing.JTextField tf_almacenamientoNumSerie;
    private javax.swing.JTextField tf_monitorDescripcion;
    private javax.swing.JTextField tf_monitorNumSerie;
    private javax.swing.JTextField tf_mouseDescripcion;
    private javax.swing.JTextField tf_mouseNumSerie;
    private javax.swing.JTextField tf_procesadorDescripcion;
    private javax.swing.JTextField tf_procesadorNumSerie;
    private javax.swing.JTextField tf_ramDescripcion;
    private javax.swing.JTextField tf_ramNumSerie;
    private javax.swing.JTextField tf_tecladoDescripcion;
    private javax.swing.JTextField tf_tecladoNumSerie;
    // End of variables declaration//GEN-END:variables
    
    private void llenarTablaDeComputadoras(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tb_computadoras.getModel();
            dtm.setRowCount(0);
            
            if (rs != null) {
                while (rs.next()) {
                    String[] fila = {rs.getString("pkId"), rs.getString("fkEstatusPc"), rs.getString("MouseDescripcion"), rs.getString("MouseNumSerie"), rs.getString("TecladoDescripcion"), rs.getString("TecladoNumSerie"), rs.getString("MonitorDescripcion"), rs.getString("MonitorNumSerie"), rs.getString("ProcesadorDescripcion"), rs.getString("ProcesadorNumSerie"), rs.getString("RamDescripcion"), rs.getString("RamNumSerie"), rs.getString("AlmacenamientoDescripcion"), rs.getString("AlmacenamientoNumSerie")};
                    dtm.addRow(fila);
                }
            }
            tb_computadoras.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: No se pudó realizar la consulta");
        }
    }
    
    private void ponerPanelesDeSalonesEnVino() {
        lb_idComputador.setText("pkId"); // Porque cuando se cambia de salon no debe quedarse el id de la computadora seleccionada
        
        pn_Las1.setBackground(COLOR_VINO);
        pn_Ldm.setBackground(COLOR_VINO);
        pn_Lds.setBackground(COLOR_VINO);
        pn_Lpg.setBackground(COLOR_VINO);
        pn_Lso.setBackground(COLOR_VINO);
        
        lb_Las1.setForeground(Color.WHITE);
        lb_Ldm.setForeground(Color.WHITE);
        lb_Lds.setForeground(Color.WHITE);
        lb_Lpg.setForeground(Color.WHITE);
        lb_Lso.setForeground(Color.WHITE);
    }
}
