/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otros;

import Clase.Estatus;
import java.awt.Color;
import java.awt.Panel;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author Geovanni
 */
public class pruebas {
    public static void main(String[] args) {
        String s = "INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS01', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM01', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS01', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG01', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO01', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS02', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM02', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS02', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG02', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO02', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS03', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM03', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS03', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG03', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO03', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS04', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM04', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS04', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG04', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO04', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS05', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM05', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS05', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG05', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO05', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS06', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM06', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS06', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG06', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO06', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS07', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM07', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS07', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG07', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO07', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS08', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM08', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS08', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG08', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO08', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS09', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM09', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS09', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG09', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO09', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS10', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM10', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS10', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG10', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO10', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS11', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM11', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS11', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG11', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO11', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS12', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM12', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS12', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG12', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO12', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS13', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM13', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS13', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG13', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO13', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS14', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM14', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS14', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG14', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO14', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS15', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM15', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS15', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG15', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO15', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS16', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM16', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS16', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG16', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO16', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS17', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM17', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS17', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG17', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO17', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS18', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM18', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS18', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG18', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO18', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS19', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM19', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS19', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG19', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO19', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS20', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM20', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS20', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG20', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO20', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS21', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM21', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS21', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG21', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO21', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS22', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM22', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS22', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG22', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO22', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS23', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM23', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS23', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG23', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO23', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS24', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM24', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS24', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG24', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO24', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS25', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM25', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS25', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG25', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO25', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS26', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM26', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS26', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG26', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO26', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS27', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM27', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS27', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG27', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO27', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS28', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM28', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS28', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG28', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO28', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS29', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM29', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS29', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG29', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO29', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS30', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM30', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS30', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG30', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO30', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS31', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM31', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS31', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG31', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO31', 'LSO', 'Disponible');\n" +
"INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LAS32', 'LAS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDM32', 'LDM', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LDS32', 'LDS', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LPG32', 'LPG', 'Disponible');	INSERT INTO Computadoras(pkId, fkSalon, fkEstatusPc) VALUES ('LSO32', 'LSO', 'Disponible');";
        s = s.replace("	", "\n");
        System.out.println(s);
    }
    
}
